from typing import Any

class PyOrchestrator:
    def __init__(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def is_running(self) -> bool: ...
    def register_star(self, name: str, handler: str) -> None: ...
    def unregister_star(self, name: str) -> None: ...
    def list_stars(self) -> list[str]: ...
    def record_activity(self) -> None: ...
    def get_stats(self, py: Any) -> dict[str, Any]: ...
    def set_protocol_connected(self, protocol: str, connected: bool) -> None: ...
    def get_protocol_status(self, protocol: str, py: Any) -> dict[str, Any] | None: ...

class PyAbpClient:
    def __init__(self) -> None: ...
    def is_connected(self) -> bool: ...
    def register_in_process_plugin(self, name: str, version: str) -> None: ...
    def register_out_of_process_plugin(
        self,
        name: str,
        version: str,
        command: str | None = None,
        transport: str | None = None,
    ) -> None: ...
    def unregister_plugin(self, name: str) -> None: ...
    def list_plugins(self) -> list[str]: ...
    def get_plugin_info(self, name: str, py: Any) -> dict[str, Any] | None: ...
    def health_check(self, name: str) -> bool: ...

# Module-level functions
def get_orchestrator() -> PyOrchestrator: ...
def get_abp_client() -> PyAbpClient: ...
def cli(args: list[str]) -> None: ...
